import { createSeedClient } from "@snaplet/seed";
import herf from "./.seed-data/harfList.json";
import ism from "./.seed-data/ismList.json";
import fill from "./.seed-data/fi'lList.json";
import suffix from "./.seed-data/suffixList.json";
import prefix from "./.seed-data/prefixList.json";

// You can use @snaplet/copycat to generate fake data for a field, for example:
// ```
// await seed.users([{ email: ({ seed }) => copycat.email(seed) }])
// ```
// More on this in our docs: https://docs.snaplet.dev/core-concepts/seed#inside-the-snapletseed-workflow
import { copycat } from "@snaplet/copycat";

// This is a basic example generated by Snaplet to start you off, check out the docs for where to go from here
// * For more on getting started with @snaplet/seed: https://docs.snaplet.dev/getting-started/quick-start/seed
// * For a more detailed reference: https://docs.snaplet.dev/core-concepts/seed

const seed = await createSeedClient({
  dryRun: process.env.DRY !== "0",
});

// Clears all existing data in the database, but keep the structure
if (process.env.RESET) await seed.$resetDatabase();

// This will create 3 records in the HttpResponses table
// it reads HttpResponses times(x) 3
await seed.collections([
  {
    id: 1,
    name: "ism",
    isDefault: true,
    description: `Ism (اسم) translates to "name" and encompasses nouns, adjectives, pronouns, and proper names. Ism words have grammatical features like gender (masculine or feminine) and number (singular, dual, or plural).`,
  },
  {
    id: 2,
    name: "Fiʻl",
    isDefault: true,
    description: `Fiʻl means "verb" and refers to words expressing actions or states of being. Arabic verbs can conjugate based on tense, person, and number.`,
  },
  {
    id: 3,
    name: "herf",
    isDefault: true,
    description: `Harf (حرف) translates to "letter" but refers to particles. These are function words that connect other words in a sentence and indicate grammatical relationships. Prepositions and conjunctions fall under this category.`,
  },
  {
    id: 4,
    name: "suffix",
    isDefault: true,
    description: `Arabic is a language with complex morphology. This means that a single Arabic word can convey a complete sentence in English. For instance, the word 'fajaʿalnāhum' (فَجَعَلْنَٰهُمُ), found in verse (23:41), translates to the English sentence 'and We made them'. In Arabic, suffixes could be attached to words to indicate the subjects and objects.`,
  },
  {
    id: 5,
    name: "prefix",
    isDefault: true,
    description: `Arabic also utilizes prefixes to add meaning and function to words. Unlike suffixes, however, these prefixes are less numerous and often serve specific grammatical purposes.  One prominent example is the definite article "al-" (الـ), which transforms indefinite nouns and adjectives into definite ones. For instance, "kitab" (كتاب) means "book," but "al-kitab" (الكتاب) translates to "the book."`,
  },
]);
await seed.wordGroups([
  // ...ism.map((wordGroup) => {
  //   return {
  //     words: wordGroup.positions,
  //     collectionId: 1,
  //     name: wordGroup.name,
  //     description: wordGroup.description,
  //   };
  // }),
  // ...fill.map((wordGroup) => {
  //   return {
  //     words: wordGroup.positions,
  //     collectionId: 2,
  //     name: wordGroup.name,
  //     description: wordGroup.description,
  //   };
  // }),

  // ...herf.map((wordGroup) => {
  //   return {
  //     words: wordGroup.positions,
  //     collectionId: 3,
  //     name: wordGroup.name,
  //     description: wordGroup.description,
  //   };
  // }),
  ...suffix.map((wordGroup) => {
    return {
      words: wordGroup.positions,
      collectionId: 4,
      name: wordGroup.name,
      description: wordGroup.description,
    };
  }),
  // ...prefix.map((wordGroup) => {
  //   return {
  //     words: wordGroup.positions,
  //     collectionId: 5,
  //     name: wordGroup.name,
  //     description: wordGroup.description,
  //   };
  // }),
]);

// Run it with: DRY=0 npx tsx seed.mts
