export const descriptions: { [key: string]: string } = {
  "Al+": 'determiner prefix ("the")',
  "bi+": 'preposition prefix ("by", "with", "in")',
  "ka+": 'preposition prefix ("like" or "thus")',
  "ta+": 'particle of oath prefix used as a preposition ("by Allah")',
  "sa+": 'prefixed particle indicating the future ("they will")',
  "ya+": 'a vocative prefix usually translated as "O"',
  "ha+": 'a vocative prefix usually translated as "Lo!"',
  "A+": 'prefix (alif) ("whether","is?", "did?", "do?")',
  "A:INTG+": 'prefixed interrogative particle ("is?", "did?", "do?")',
  "A:EQ+": 'prefixed equalization particle ("whether")',

  "w:CONJ+": 'conjunction prefix ("and")',
  "w:REM+": 'resumption prefix ("then" or "so")',
  "w:CIRC+": 'circumstantial prefix ("while")',
  "w:SUP+": 'supplemental prefix ("then" or "so")',
  "w:P+": 'particle of oath prefix used as a preposition ("by the pen")',
  "w:COM+": 'comitative prefix ("with")',

  "f:REM+": 'resumption prefix ("then" or "so")',
  "f:CONJ+": 'conjunction prefix ("and")',
  "f:RSLT+": 'result prefix ("then")',
  "f:SUP+": 'supplemental prefix ("then" or "so")',
  "f:CAUS+": 'cause prefix ("then" or "so")',

  "l:P+": " the letter lām as a prefixed preposition",
  "l:EMPH+": "the letter lām as a prefixed particle used to give emphasis",
  "l:PRP+": "the letter lām as a prefixed particle used to indicate purpose",
  "l:IMPV+": "the letter lām as a prefixed particle used to form an imperative",
};
