import * as createData from "./createData";
import * as createWordCount from "./createWordCount";
import * as createRootData from "./createRootData";
import * as createHarfList from "./harf/createList";
import * as createIsmNFilList from "./ism & fi'l/createList";
import * as createPrefixList from "./prefix/createList";
import * as createSuffixList from "./suffix/createList";
await createData;
await createWordCount;
await createRootData;
await createHarfList;
await createIsmNFilList;
await createPrefixList;
await createSuffixList;
