create table
  public.collections (
    id bigint generated by default as identity,
    name text not null,
    description text null,
    collection json not null,
    "is_default" boolean null default false,
    constraint collections_pkey primary key (id),
    constraint collections_id_key unique (id)
  ) tablespace pg_default;
  
  alter table "public"."collections" enable row level security;

create policy "Enable SELECT for authenticated users only"
on "public"."collections"
as permissive
for select
to authenticated
using (true);
