create table
  public.user_progress (
    id bigint generated by default as identity,
    list bigint not null,
    "user" uuid not null,
    progress json not null,
    constraint user_progress_pkey primary key (id),
    constraint user_progress_list_fkey foreign key (list) references lists (id) on delete cascade,
    constraint user_progress_user_fkey foreign key ("user") references auth.users (id) on delete cascade
  ) tablespace pg_default;

create policy "user can only modify their own data"
on "public"."user_progress"
as permissive
for all
to public
using ((auth.uid() = "user"))
with check ((auth.uid() = "user"));