create table
  public.user_to_list (
    id bigint generated by default as identity,
    "user" uuid not null,
    list bigint not null,
    constraint user_to_list_pkey primary key (id),
    constraint user_to_list_user_fkey foreign key ("user") references auth.users (id) on delete cascade,
    constraint user_to_list_list_fkey foreign key (list) references lists (id) on delete cascade
  ) tablespace pg_default;


CREATE POLICY "user can only modify their own data" ON "public"."user_to_list"
AS PERMISSIVE FOR ALL
TO public
USING (auth.uid() = user_to_list.user)
WITH CHECK (auth.uid() = user_to_list.user)