create table
  public.user_progress (
    id bigint generated by default as identity,
    collection_id bigint not null,
    "user_id" uuid not null,
    progress json not null,
    constraint user_progress_pkey primary key (id),
    constraint user_progress_collection_fkey foreign key (collection_id) references collections (id) on delete cascade,
    constraint user_progress_user_fkey foreign key ("user_id") references auth.users (id) on delete cascade
  ) tablespace pg_default;
  
  
alter table "public"."user_progress" enable row level security;
create policy "user can only modify their own data"
on "public"."user_progress"
as permissive
for all
to public
using ((auth.uid() = "user_id"))
with check ((auth.uid() = "user_id"));