create table
  public.user_preference (
    id bigint generated by default as identity,
    "user" uuid not null default auth.uid (),
    translation_id bigint not null default '131'::bigint,
    intervals json not null default '"{25:86400000,50:864000000,75:2592000000,100:15552000000}"'::json,
    constraint user_preference_pkey primary key (id),
    constraint public_user_preference_user_fkey foreign key ("user") references auth.users (id) on update cascade on delete cascade
  ) tablespace pg_default;

  alter table "public"."user_preference" enable row level security;

create policy "user can only modify their own data"
on "public"."user_preference"
as permissive
for all
to public
using ((auth.uid() = "user"))
with check ((auth.uid() = "user"));