create table
  public.user_to_collection (
    id bigint generated by default as identity,
    "user_id" uuid not null,
    collection bigint not null,
    constraint user_to_collection_pkey primary key (id),
    constraint user_to_collection_user_fkey foreign key ("user_id") references auth.users (id) on delete cascade,
    constraint user_to_collection_collection_fkey foreign key (collection) references collections (id) on delete cascade
  ) tablespace pg_default;

alter table "public"."user_to_collection" enable row level security;

CREATE POLICY "user can only modify their own data" ON "public"."user_to_collection"
AS PERMISSIVE FOR ALL
TO public
USING (auth.uid() = user_to_collection.user_id)
WITH CHECK (auth.uid() = user_to_collection.user_id)