export const descriptions: { [key: string]: string } = {
  P: "Preposition",
  EMPH: "Emphatic lām prefix",
  IMPV: "Imperative lām prefix",
  PRP: "Purpose lām prefix",
  CONJ: "Coordinating conjunction",
  SUB: "Subordinating conjunctionA",
  ACC: "Accusative particle",
  AMD: "Amendment particle",
  ANS: "Answer particle",
  AVR: "Aversion particle",
  CAUS: "Particle of cause",
  CERT: "Particle of certainty",
  CIRC: "Circumstantial particle",
  COM: "Comitative particle",
  COND: "Conditional particle",

  EQ: "Equalization particle",
  EXH: "Exhortation particle",
  EXL: "Explanation particle",
  EXP: "Exceptive particle",
  FUT: "Future particle",
  INC: "Inceptive particle",
  INT: "Particle of interpretation",
  INTG: "Interogative particle",
  NEG: "Negative particle",
  PREV: "Preventive particle",
  PRO: "Prohibition particle",
  REM: "Resumption particle",
  RES: "Restriction particle",
  RET: "Retraction particle",
  RSLT: "Result particle",
  SUP: "Supplemental particle",
  SUR: "Surprise particle",
  VOC: "Vocative particle",
  INL: "Quranic initials",
};
